package com.dkit.Sd2a.ethan.sia;

public enum MainMenu
{
    QUIT_APPLICATION,
    ADD_STUDENT,
    DELETE_STUDENT,
    EDIT_STUDENT,
    FIND_STUDENT,
    DISPLAY_STUDENT,
    ADD_BOOKING,
    DELETE_BOOKING,
    PRINT_BOOKING,
    RETURN_COMPUTER,
    PRINT_BOOKING_IN_DATE_TIME,
    DISPLAY_AVERAGE_LENGTH_OF_ALL_BOOKING,
    PRINT_STATISTIC;



}
